# Details
This a sample project of mine to refresh related concepts.
Say in your a university, generally people who's average CGPA is more than or equal 3.7 tend to get A in Neural Network course, likewise who's CGPA is >= 3.3 gets A - and who's CGPA is >= 3 tend to get B+ maximum time.
We'll first build a sample dataset and then make a deeplearning model, which will predict someone's grade in Neural Network course based on his average CGPA.

We'll consider A as 0, A- as 1, B+ as 2

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

**Sample Dataset Building**
Here we are making a sample dataset. <br>
Where for 90% of the students, <br>
CGPA>=3.7 A ~ 0 <br>
CGPA>=3.3 A- ~ 1 <br>
CGPA>=3.0 B+ ~ 2 <br>

Where for 3% of the students,<br>
CGPA>=3.3 A- ~ 1 <br>
CGPA>=3.7 A ~ 0 <br>
CGPA>=3.0 B+ ~ 2 <br>

Where for 3% of the students,<br>
CGPA>=3.3 A- ~ 1 <br>
CGPA>=3.0 B+ ~ 2 <br>
CGPA>=3.7 A ~ 0 <br>

Where for 3% of the students,<br>
CGPA>=3.7 A ~ 0 <br>
CGPA>=3.0 B+ ~ 2 <br>
CGPA>=3.3 A- ~ 1 <br>

In [3]:
import numpy as np
import sklearn
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
import random
train_labels=[]
train_samples = []

for i in range(910):
    # The ~90% of students who's average CGPA is greater than or equal 3.7
    random_student_A = random.uniform(3.7,4)
    train_samples.append(random_student_A)
    train_labels.append(0)

    # The ~90% of students who's average CGPA is greater than or equal 3.3
    random_student_A_minus = random.uniform(3.3,3.69)
    train_samples.append(random_student_A_minus)
    train_labels.append(1)
    
    # The ~90% of students who's average CGPA is greater than or equal 3.3
    random_student_B_plus= random.uniform(3.00,3.29)
    train_samples.append(random_student_B_plus)
    train_labels.append(2)
    

for i in range(30):
     # The ~3% of students who's average CGPA is greater than or equal 3.7
    random_student_A = random.uniform(3.7,4)
    train_samples.append(random_student_A)
    train_labels.append(1)

    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_A_minus = random.uniform(3.3,3.69)
    train_samples.append(random_student_A_minus)
    train_labels.append(0)
    
    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_B_plus= random.uniform(3.00,3.29)
    train_samples.append(random_student_B_plus)
    train_labels.append(2)
    
for i in range(30):
       # The ~3% of students who's average CGPA is greater than or equal 3.7
    random_student_A = random.uniform(3.7,4)
    train_samples.append(random_student_A)
    train_labels.append(1)

    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_A_minus = random.uniform(3.3,3.69)
    train_samples.append(random_student_A_minus)
    train_labels.append(2)
    
    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_B_plus= random.uniform(3.00,3.29)
    train_samples.append(random_student_B_plus)
    train_labels.append(0)
    
for i in range(30):
      # The ~3% of students who's average CGPA is greater than or equal 3.7
    random_student_A = random.uniform(3.7,4)
    train_samples.append(random_student_A)
    train_labels.append(0)

    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_A_minus = random.uniform(3.3,3.69)
    train_samples.append(random_student_A_minus)
    train_labels.append(2)
    
    # The ~3% of students who's average CGPA is greater than or equal 3.3
    random_student_B_plus= random.uniform(3.00,3.29)
    train_samples.append(random_student_B_plus)
    train_labels.append(1)


train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

# for i,j in zip(train_samples,train_labels):
#     print(str(i) + "," + str(j))


scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

for i in scaled_train_samples:
   print(i)


[0.66723149]
[0.01599654]
[0.64469557]
[0.22562873]
[0.72587083]
[0.91087308]
[0.45135988]
[0.18331073]
[0.41169931]
[0.963379]
[0.03133344]
[0.57264673]
[0.47287373]
[0.74191919]
[0.13732337]
[0.21579676]
[0.35656992]
[0.39251688]
[0.02503206]
[0.82193369]
[0.47594052]
[0.09486319]
[0.15888847]
[0.4461222]
[0.74315803]
[0.6329053]
[0.01411701]
[0.79697061]
[0.59215242]
[0.78295892]
[0.40559518]
[0.78746031]
[0.03851339]
[0.79770139]
[0.80241622]
[0.9734416]
[0.8732004]
[0.48718568]
[0.53035721]
[0.0749232]
[0.99793564]
[0.4192876]
[0.89643031]
[0.16932353]
[0.84082778]
[0.97576903]
[0.37611753]
[0.86101663]
[0.46354247]
[0.7863132]
[0.00718484]
[0.84620154]
[0.31203405]
[0.90417887]
[0.04646539]
[0.1607698]
[0.89645601]
[0.45398558]
[0.16118884]
[0.78794478]
[0.3925377]
[0.68888572]
[0.74644011]
[0.80081384]
[0.70438637]
[0.7845304]
[0.21098123]
[0.85265383]
[0.31614997]
[0.20978324]
[0.9576572]
[0.78270817]
[0.5603049]
[0.8484506]
[0.76974317]
[0.50432873]
[0.67885218]
[0.25955077]
[

[0.23005857]
[0.08311559]
[0.06811032]
[0.75427932]
[0.22481185]
[0.19601302]
[0.38054711]
[0.09339266]
[0.42529692]
[0.59373139]
[0.82431778]
[0.59703023]
[0.25097316]
[0.32575522]
[0.98879211]
[0.44288613]
[0.20913356]
[0.96259412]
[0.49657942]
[0.01042036]
[0.10443792]
[0.76430633]
[0.59578001]
[0.22235474]
[0.03605669]
[0.19016961]
[0.95845062]
[0.93833254]
[0.93481329]
[0.37392844]
[0.81133192]
[0.4678593]
[0.41925125]
[0.43984278]
[0.16472485]
[0.15791536]
[0.87085144]
[0.58519015]
[0.42818156]
[0.36948148]
[0.97515872]
[0.73164381]
[0.37114982]
[0.71335681]
[0.70915827]
[0.26854394]
[0.85939197]
[0.63134542]
[0.88869709]
[0.03055735]
[0.07796386]
[0.09259115]
[0.87126451]
[0.28499285]
[0.2001935]
[0.16467721]
[0.02877705]
[0.10694487]
[0.78347243]
[0.94701222]
[0.59230132]
[0.19084318]
[0.3033386]
[0.79690753]
[0.2491396]
[0.72227761]
[0.06923198]
[0.02788565]
[0.30936657]
[0.01489343]
[0.30949828]
[0.91220566]
[0.08788545]
[0.91292761]
[0.90264402]
[0.5928705]
[0.22911857]
[0.7

[0.44512695]
[0.65372328]
[0.07978787]
[0.23714195]
[0.91963001]
[0.26772546]
[0.66427806]
[0.4232526]
[0.40675363]
[0.67654801]
[0.96456205]
[0.47145606]
[0.96731614]
[0.5840562]
[0.35091248]
[0.44689132]
[0.43323632]
[0.97873182]
[0.25736616]
[0.86158903]
[0.30186937]
[0.87010132]
[0.92089042]
[0.91879103]
[0.03929156]
[0.05473674]
[0.45701831]
[0.27232065]
[0.82156248]
[0.8977173]
[0.38082681]
[0.02967902]
[0.4754933]
[0.89498343]
[0.86786655]
[0.62538556]
[0.54186028]
[0.54869409]
[0.18773332]
[0.42784812]
[0.41850404]
[0.94429505]
[0.51078306]
[0.8167515]
[0.51337252]
[0.35076461]
[0.72273988]
[0.10042071]
[0.06897324]
[0.18656027]
[0.0704099]
[0.34217248]
[0.06559779]
[0.50717985]
[0.82542893]
[0.79486937]
[0.79738561]
[0.40297596]
[0.79266197]
[0.10594532]
[0.48615805]
[0.16203098]
[0.61968869]
[0.00145179]
[0.31659865]
[0.31867903]
[0.59491557]
[0.11576373]
[0.63746473]
[0.84700716]
[0.76587162]
[0.72594804]
[0.30733959]
[0.07622375]
[0.46553801]
[0.07711635]
[0.65246459]
[0.13

[0.50208346]
[0.46881587]
[0.77329378]
[0.50926887]
[0.77242827]
[0.30614626]
[0.7206026]
[0.93294194]
[0.32613287]
[0.44941689]
[0.93965661]
[0.50470894]
[0.0347998]
[0.86453183]
[0.13328063]
[0.20147624]
[0.25765819]
[0.81632082]
[0.79460925]
[0.63823196]
[0.980968]
[0.80010294]
[0.55129899]
[0.77045849]
[0.06700696]
[0.97420039]
[0.25722671]
[0.42283534]
[0.38263666]
[0.22957214]
[0.77051499]
[0.89948124]
[0.81561995]
[0.97510246]
[0.78590927]
[0.85851342]
[0.27774553]
[0.14314786]
[0.79476985]
[0.09422887]
[0.05240947]
[0.39353905]
[0.5426022]
[0.63140849]
[0.43899246]
[0.72459729]
[0.60095211]
[0.36510771]
[0.60266162]
[0.09134809]
[0.86071992]
[0.61322276]
[0.40328952]
[0.8794602]
[0.67464789]
[0.71527734]
[0.68987105]
[0.22732449]
[0.66625411]
[0.11279551]
[0.09813505]
[0.49555162]
[0.90585626]
[0.74560364]
[0.91728521]
[0.82047187]
[0.75588713]
[0.39000935]
[0.67774371]
[0.09734582]
[0.79151281]
[0.85269889]
[0.23937706]
[0.25055248]
[0.727312]
[0.82936527]
[0.78595299]
[0.9877

In [12]:
model = model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, validation_split = 0.1,verbose=2)([
    Dense(units = 16, input_shape=(1,), activation = 'relu'),
    Dense(units = 32, activation = 'relu'),
    Dense(units = 64, activation = 'relu'),
    Dense(units = 128, activation = 'relu'),
    Dense(units = 3, activation = 'softmax'),
])

In [13]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_9 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 387       
Total params: 11,395
Trainable params: 11,395
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [15]:
model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, validation_split = 0.1,verbose=2)

Epoch 1/30
270/270 - 1s - loss: 1.0375 - accuracy: 0.5359 - val_loss: 0.9380 - val_accuracy: 0.6733
Epoch 2/30
270/270 - 0s - loss: 0.7762 - accuracy: 0.6996 - val_loss: 0.6412 - val_accuracy: 0.7533
Epoch 3/30
270/270 - 0s - loss: 0.5488 - accuracy: 0.8189 - val_loss: 0.5199 - val_accuracy: 0.8400
Epoch 4/30
270/270 - 0s - loss: 0.4558 - accuracy: 0.8730 - val_loss: 0.4762 - val_accuracy: 0.8900
Epoch 5/30
270/270 - 0s - loss: 0.4195 - accuracy: 0.8989 - val_loss: 0.4650 - val_accuracy: 0.9100
Epoch 6/30
270/270 - 0s - loss: 0.4041 - accuracy: 0.9093 - val_loss: 0.4527 - val_accuracy: 0.9000
Epoch 7/30
270/270 - 0s - loss: 0.3947 - accuracy: 0.9141 - val_loss: 0.4485 - val_accuracy: 0.9000
Epoch 8/30
270/270 - 0s - loss: 0.3883 - accuracy: 0.9144 - val_loss: 0.4460 - val_accuracy: 0.9000
Epoch 9/30
270/270 - 0s - loss: 0.3834 - accuracy: 0.9159 - val_loss: 0.4384 - val_accuracy: 0.9133
Epoch 10/30
270/270 - 0s - loss: 0.3802 - accuracy: 0.9200 - val_loss: 0.4354 - val_accuracy: 0.9100

# Testing
Normally we build a test set and test with that. However I'll test with only one or two datas. Say a student has average CGPA of 3.78 and another has 3.32 last one has 3.02.

In [16]:
test_samples = np.array([3.78, 3.32, 3.02])
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))
predictions = model.predict(x=scaled_test_samples,batch_size=10,verbose=0)
for i in predictions:
    print(i)

[9.7014856e-01 2.9198235e-02 6.5318274e-04]
[0.01937801 0.90151966 0.07910229]
[0.0198927  0.01769791 0.96240944]


In [17]:
rounded_predictions = np.argmax(predictions, axis=-1)

for i in rounded_predictions:
    print(i)

0
1
2


So, we can see the result is as expected. If one has average cgpa of 3.87 he would get A, 3.32 would <br>
get A- and 3.02 would get B+. Which is exactly what should happen for the most part.